// Generated by fable/tools/build_report_data.py — do not edit by hand.
window.FABLE_DATA = {
  "built_at": "2026-06-10T22:26:48Z",
  "corpus": {
    "manifest_matches": 125,
    "rated_matches": 107,
    "players": 35,
    "first_match": "2026-04-16T01:27:48.447651+00:00",
    "last_match": "2026-06-07T02:24:17.905988+00:00",
    "rows_excluded_campod": 15,
    "rows_excluded_low_activity": 7,
    "matches_excluded_low_player_count": 13,
    "matches_excluded_short_duration": 5,
    "elo_schema_version": 10,
    "computed_at": "2026-06-07T09:56:43Z"
  },
  "ratings": [
    {
      "name": "VTrider",
      "vtsr": 1741.5,
      "peak": 1742.4,
      "matches": 51,
      "cmdr": 3,
      "provisional": false,
      "lift": 0.0
    },
    {
      "name": "Snake",
      "vtsr": 1699.9,
      "peak": 1753.0,
      "matches": 49,
      "cmdr": 26,
      "provisional": false,
      "lift": 0.0
    },
    {
      "name": "Cyber",
      "vtsr": 1682.7,
      "peak": 1721.9,
      "matches": 23,
      "cmdr": 4,
      "provisional": false,
      "lift": 0.0
    },
    {
      "name": "Domakus",
      "vtsr": 1680.6,
      "peak": 1748.8,
      "matches": 56,
      "cmdr": 6,
      "provisional": false,
      "lift": 0.0
    },
    {
      "name": "Sly",
      "vtsr": 1658.9,
      "peak": 1681.4,
      "matches": 6,
      "cmdr": 1,
      "provisional": true,
      "lift": 0.0
    },
    {
      "name": "MAX",
      "vtsr": 1642.0,
      "peak": 1642.0,
      "matches": 4,
      "cmdr": 2,
      "provisional": true,
      "lift": 0.0
    },
    {
      "name": "tom",
      "vtsr": 1636.4,
      "peak": 1636.4,
      "matches": 10,
      "cmdr": 1,
      "provisional": false,
      "lift": 0.0
    },
    {
      "name": "Nomad",
      "vtsr": 1626.1,
      "peak": 1646.4,
      "matches": 68,
      "cmdr": 11,
      "provisional": false,
      "lift": 0.0
    },
    {
      "name": "blue",
      "vtsr": 1618.6,
      "peak": 1618.6,
      "matches": 23,
      "cmdr": 14,
      "provisional": false,
      "lift": 0.0
    },
    {
      "name": "Sev",
      "vtsr": 1613.0,
      "peak": 1613.0,
      "matches": 62,
      "cmdr": 30,
      "provisional": false,
      "lift": 0.0
    },
    {
      "name": "Muffin",
      "vtsr": 1599.7,
      "peak": 1599.7,
      "matches": 15,
      "cmdr": 1,
      "provisional": false,
      "lift": 0.0
    },
    {
      "name": "Vivify",
      "vtsr": 1583.1,
      "peak": 1614.5,
      "matches": 45,
      "cmdr": 1,
      "provisional": false,
      "lift": 0.0
    },
    {
      "name": "F9bomber",
      "vtsr": 1557.9,
      "peak": 1578.8,
      "matches": 90,
      "cmdr": 19,
      "provisional": false,
      "lift": 0.0
    },
    {
      "name": "Certified Bad Guy",
      "vtsr": 1548.8,
      "peak": 1583.2,
      "matches": 51,
      "cmdr": 14,
      "provisional": false,
      "lift": 0.0
    },
    {
      "name": "econchump",
      "vtsr": 1536.3,
      "peak": 1570.7,
      "matches": 33,
      "cmdr": 5,
      "provisional": false,
      "lift": 0.0
    },
    {
      "name": "Cloaket",
      "vtsr": 1529.7,
      "peak": 1606.9,
      "matches": 30,
      "cmdr": 14,
      "provisional": false,
      "lift": 0.0
    },
    {
      "name": "Infinity",
      "vtsr": 1518.5,
      "peak": 1518.5,
      "matches": 3,
      "cmdr": 1,
      "provisional": true,
      "lift": 0.0
    },
    {
      "name": "Darkhooded2",
      "vtsr": 1515.1,
      "peak": 1515.1,
      "matches": 1,
      "cmdr": 0,
      "provisional": true,
      "lift": 0.0
    },
    {
      "name": "Zack",
      "vtsr": 1508.8,
      "peak": 1530.5,
      "matches": 3,
      "cmdr": 0,
      "provisional": true,
      "lift": 0.0
    },
    {
      "name": "sponge",
      "vtsr": 1506.5,
      "peak": 1518.8,
      "matches": 27,
      "cmdr": 0,
      "provisional": false,
      "lift": 0.0
    },
    {
      "name": "Herp McDerperson",
      "vtsr": 1501.1,
      "peak": 1510.5,
      "matches": 23,
      "cmdr": 3,
      "provisional": false,
      "lift": 0.0
    },
    {
      "name": "Lamper",
      "vtsr": 1485.5,
      "peak": 1536.4,
      "matches": 14,
      "cmdr": 3,
      "provisional": false,
      "lift": 0.0
    },
    {
      "name": "DesUxSAsU",
      "vtsr": 1484.5,
      "peak": 1510.9,
      "matches": 3,
      "cmdr": 3,
      "provisional": true,
      "lift": 0.0
    },
    {
      "name": "Lithium",
      "vtsr": 1482.6,
      "peak": 1539.9,
      "matches": 66,
      "cmdr": 18,
      "provisional": false,
      "lift": 0.0
    },
    {
      "name": "Shock",
      "vtsr": 1468.0,
      "peak": 1500.0,
      "matches": 1,
      "cmdr": 0,
      "provisional": true,
      "lift": 0.0
    },
    {
      "name": "vacuum34",
      "vtsr": 1456.4,
      "peak": 1500.0,
      "matches": 4,
      "cmdr": 4,
      "provisional": true,
      "lift": 0.06
    },
    {
      "name": "M.S",
      "vtsr": 1455.1,
      "peak": 1517.3,
      "matches": 7,
      "cmdr": 1,
      "provisional": true,
      "lift": 0.1417
    },
    {
      "name": "Waddles",
      "vtsr": 1455.1,
      "peak": 1500.0,
      "matches": 28,
      "cmdr": 2,
      "provisional": false,
      "lift": 0.1867
    },
    {
      "name": "dd",
      "vtsr": 1447.1,
      "peak": 1520.1,
      "matches": 25,
      "cmdr": 5,
      "provisional": false,
      "lift": 0.3383
    },
    {
      "name": "Sahd0w",
      "vtsr": 1440.7,
      "peak": 1500.0,
      "matches": 2,
      "cmdr": 0,
      "provisional": true,
      "lift": 0.3467
    },
    {
      "name": "judgeguns",
      "vtsr": 1440.6,
      "peak": 1500.0,
      "matches": 38,
      "cmdr": 1,
      "provisional": false,
      "lift": 0.6933
    },
    {
      "name": "The_Bylarge",
      "vtsr": 1439.7,
      "peak": 1500.0,
      "matches": 8,
      "cmdr": 0,
      "provisional": true,
      "lift": 0.3783
    },
    {
      "name": "appel",
      "vtsr": 1434.3,
      "peak": 1500.0,
      "matches": 3,
      "cmdr": 0,
      "provisional": true,
      "lift": 0.4817
    },
    {
      "name": "Darkvale",
      "vtsr": 1420.9,
      "peak": 1524.5,
      "matches": 46,
      "cmdr": 19,
      "provisional": false,
      "lift": 0.7367
    },
    {
      "name": "Monkey",
      "vtsr": 1415.6,
      "peak": 1500.0,
      "matches": 22,
      "cmdr": 2,
      "provisional": false,
      "lift": 1.0
    }
  ],
  "rating_stats": {
    "mean": 1538.0,
    "median": 1515.1,
    "min": 1415.6,
    "max": 1741.5,
    "above_anchor": 21,
    "below_anchor": 14
  },
  "economy": {
    "labels": [
      "2026-04-16",
      "2026-04-16",
      "2026-04-16",
      "2026-04-16",
      "2026-04-17",
      "2026-04-17",
      "2026-04-18",
      "2026-04-18",
      "2026-04-21",
      "2026-04-21",
      "2026-04-22",
      "2026-04-22",
      "2026-04-22",
      "2026-04-23",
      "2026-04-23",
      "2026-04-23",
      "2026-04-24",
      "2026-04-24",
      "2026-04-24",
      "2026-04-26",
      "2026-04-26",
      "2026-04-26",
      "2026-04-26",
      "2026-04-26",
      "2026-04-26",
      "2026-04-27",
      "2026-04-27",
      "2026-04-29",
      "2026-04-29",
      "2026-04-29",
      "2026-04-29",
      "2026-04-29",
      "2026-04-29",
      "2026-04-29",
      "2026-04-29",
      "2026-04-30",
      "2026-04-30",
      "2026-04-30",
      "2026-04-30",
      "2026-04-30",
      "2026-05-01",
      "2026-05-01",
      "2026-05-03",
      "2026-05-03",
      "2026-05-04",
      "2026-05-04",
      "2026-05-04",
      "2026-05-04",
      "2026-05-04",
      "2026-05-05",
      "2026-05-08",
      "2026-05-08",
      "2026-05-09",
      "2026-05-09",
      "2026-05-09",
      "2026-05-09",
      "2026-05-09",
      "2026-05-09",
      "2026-05-12",
      "2026-05-12",
      "2026-05-12",
      "2026-05-14",
      "2026-05-14",
      "2026-05-14",
      "2026-05-14",
      "2026-05-14",
      "2026-05-14",
      "2026-05-15",
      "2026-05-15",
      "2026-05-15",
      "2026-05-15",
      "2026-05-15",
      "2026-05-16",
      "2026-05-16",
      "2026-05-16",
      "2026-05-16",
      "2026-05-16",
      "2026-05-16",
      "2026-05-16",
      "2026-05-16",
      "2026-05-17",
      "2026-05-17",
      "2026-05-17",
      "2026-05-17",
      "2026-05-19",
      "2026-05-19",
      "2026-05-21",
      "2026-05-21",
      "2026-05-21",
      "2026-05-21",
      "2026-05-22",
      "2026-05-22",
      "2026-05-22",
      "2026-05-22",
      "2026-05-22",
      "2026-05-22",
      "2026-05-22",
      "2026-05-22",
      "2026-05-22",
      "2026-05-24",
      "2026-05-29",
      "2026-06-01",
      "2026-06-05",
      "2026-06-07",
      "2026-06-07",
      "2026-06-07",
      "2026-06-07"
    ],
    "per_match_net": [
      45.1,
      52.76,
      41.99,
      25.83,
      32.53,
      54.94,
      10.37,
      9.0,
      4.13,
      27.73,
      3.19,
      32.57,
      12.95,
      8.37,
      22.17,
      15.11,
      -10.66,
      6.71,
      37.95,
      5.48,
      -3.42,
      -3.16,
      6.4,
      14.75,
      23.86,
      -6.75,
      -18.42,
      3.93,
      8.21,
      -5.49,
      17.95,
      29.34,
      25.9,
      34.3,
      26.8,
      -3.41,
      4.45,
      10.57,
      10.26,
      1.23,
      18.61,
      9.08,
      -3.97,
      -27.0,
      11.3,
      1.75,
      -10.19,
      0.07,
      -2.07,
      2.82,
      13.13,
      -17.75,
      13.83,
      3.9,
      7.6,
      6.99,
      -6.07,
      2.04,
      21.68,
      12.38,
      27.48,
      -6.31,
      3.59,
      -15.16,
      -9.23,
      7.58,
      -26.34,
      -9.23,
      20.58,
      3.57,
      0.45,
      6.6,
      31.38,
      21.4,
      -4.58,
      26.56,
      11.94,
      27.06,
      16.18,
      10.73,
      9.95,
      14.59,
      43.34,
      52.14,
      20.58,
      19.94,
      13.51,
      0.0,
      12.17,
      15.04,
      30.7,
      32.66,
      23.16,
      2.77,
      14.04,
      15.73,
      34.62,
      -0.03,
      6.21,
      16.03,
      62.21,
      -9.23,
      9.79,
      8.33,
      20.8,
      33.17,
      11.23
    ],
    "cumulative_net": [
      45.1,
      97.9,
      139.8,
      165.7,
      198.2,
      253.2,
      263.5,
      272.5,
      276.6,
      304.4,
      307.6,
      340.1,
      353.1,
      361.5,
      383.6,
      398.7,
      388.1,
      394.8,
      432.7,
      438.2,
      434.8,
      431.6,
      438.0,
      452.8,
      476.6,
      469.9,
      451.5,
      455.4,
      463.6,
      458.1,
      476.1,
      505.4,
      531.3,
      565.6,
      592.4,
      589.0,
      593.5,
      604.0,
      614.3,
      615.5,
      634.1,
      643.2,
      639.2,
      612.2,
      623.5,
      625.3,
      615.1,
      615.2,
      613.1,
      615.9,
      629.0,
      611.3,
      625.1,
      629.0,
      636.6,
      643.6,
      637.5,
      639.6,
      661.3,
      673.6,
      701.1,
      694.8,
      698.4,
      683.2,
      674.0,
      681.6,
      655.3,
      646.0,
      666.6,
      670.2,
      670.6,
      677.2,
      708.6,
      730.0,
      725.4,
      752.0,
      763.9,
      791.0,
      807.2,
      817.9,
      827.8,
      842.4,
      885.8,
      937.9,
      958.5,
      978.4,
      991.9,
      991.9,
      1004.1,
      1019.2,
      1049.9,
      1082.5,
      1105.7,
      1108.5,
      1122.5,
      1138.2,
      1172.8,
      1172.8,
      1179.0,
      1195.0,
      1257.3,
      1248.0,
      1257.8,
      1266.1,
      1286.9,
      1320.1,
      1331.3
    ],
    "total_gained": 6275.5,
    "total_lost": -4944.2,
    "net_created": 1331.3
  },
  "weights": {
    "net_damage_share": 0.2,
    "thug_kill_rate": 0.2,
    "thug_accuracy": 0.15,
    "thug_efficiency": 0.16,
    "pve_share": 0.12,
    "mobility": 0.08,
    "snipe_bonus": 0.005,
    "target_lock_pct": 0.005
  },
  "weights_pre_v210": {
    "net_damage_share": 0.2,
    "thug_kill_rate": 0.2,
    "thug_accuracy": 0.15,
    "thug_efficiency": 0.16,
    "pve_share": 0.12,
    "mobility": 0.08,
    "snipe_bonus": 0.05,
    "target_lock_pct": 0.04
  },
  "commander": {
    "prior": {
      "mobility": -0.488,
      "thug_kill_rate": -0.164,
      "net_damage_share": -0.131,
      "thug_efficiency": -0.106,
      "target_lock_pct": -0.1,
      "pve_share": -0.05
    },
    "observed": {
      "mobility": {
        "n": 214,
        "running_mean": -0.3458,
        "shrunk_baseline_at_corpus_end": -0.3633,
        "locked": false
      },
      "thug_kill_rate": {
        "n": 214,
        "running_mean": -0.0712,
        "shrunk_baseline_at_corpus_end": -0.0826,
        "locked": false
      },
      "net_damage_share": {
        "n": 214,
        "running_mean": -0.0608,
        "shrunk_baseline_at_corpus_end": -0.0694,
        "locked": false
      },
      "thug_efficiency": {
        "n": 214,
        "running_mean": -0.113,
        "shrunk_baseline_at_corpus_end": -0.1121,
        "locked": false
      },
      "target_lock_pct": {
        "n": 198,
        "running_mean": -0.3913,
        "shrunk_baseline_at_corpus_end": -0.1,
        "locked": true
      },
      "pve_share": {
        "n": 214,
        "running_mean": 0.0489,
        "shrunk_baseline_at_corpus_end": -0.05,
        "locked": true
      }
    },
    "shrinkage": 30.0,
    "locked_axes": [
      "pve_share",
      "target_lock_pct"
    ]
  },
  "validator": {
    "generated": "2026-06-10T22:23:35Z",
    "raw": {
      "rank_correlation": {
        "pooled_rho": 0.44495956523226865,
        "pooled_n_pairs": 940,
        "per_match_rho_mean": 0.41436132541725434,
        "per_match_rho_median": 0.503030303030303,
        "per_match_rho_stdev": 0.3542347677106358,
        "per_match_n_runs": 106
      },
      "calibration": {
        "buckets": [
          {
            "gap_min": -176.3599999999999,
            "gap_max": -91.13000000000011,
            "gap_mean": -121.2923404255319,
            "n": 94,
            "observed_p_mean": -0.15070744680851064,
            "predicted_e_mean": -0.1726182333986349,
            "residual": 0.02191078659012427
          },
          {
            "gap_min": -89.55999999999995,
            "gap_max": -59.539999999999964,
            "gap_mean": -72.40234042553192,
            "n": 94,
            "observed_p_mean": -0.08937234042553191,
            "predicted_e_mean": -0.10380164787025581,
            "residual": 0.014429307444723899
          },
          {
            "gap_min": -59.22000000000003,
            "gap_max": -32.950000000000045,
            "gap_mean": -45.23138297872338,
            "n": 94,
            "observed_p_mean": -0.07769680851063829,
            "predicted_e_mean": -0.06499341266889848,
            "residual": -0.012703395841739809
          },
          {
            "gap_min": -32.789999999999964,
            "gap_max": -14.545000000000073,
            "gap_mean": -22.39436170212763,
            "n": 94,
            "observed_p_mean": 0.0039702127659574475,
            "predicted_e_mean": -0.032214829048306304,
            "residual": 0.036185041814263755
          },
          {
            "gap_min": -14.519999999999982,
            "gap_max": 0.0,
            "gap_mean": -8.21265957446807,
            "n": 94,
            "observed_p_mean": -0.023803191489361705,
            "predicted_e_mean": -0.011818005643135815,
            "residual": -0.01198518584622589
          },
          {
            "gap_min": 0.0,
            "gap_max": 17.069999999999936,
            "gap_mean": 7.798031914893601,
            "n": 94,
            "observed_p_mean": -0.003791489361702128,
            "predicted_e_mean": 0.011221204862995037,
            "residual": -0.015012694224697165
          },
          {
            "gap_min": 17.11999999999989,
            "gap_max": 41.34999999999991,
            "gap_mean": 29.143510638297876,
            "n": 94,
            "observed_p_mean": 0.0496,
            "predicted_e_mean": 0.04191196352947918,
            "residual": 0.007688036470520819
          },
          {
            "gap_min": 41.455000000000155,
            "gap_max": 82.14999999999986,
            "gap_mean": 60.385053191489355,
            "n": 94,
            "observed_p_mean": 0.09252765957446808,
            "predicted_e_mean": 0.08665713447610626,
            "residual": 0.00587052509836182
          },
          {
            "gap_min": 82.15999999999985,
            "gap_max": 155.37000000000012,
            "gap_mean": 122.54101063829786,
            "n": 94,
            "observed_p_mean": 0.2045351063829787,
            "predicted_e_mean": 0.17437918586773193,
            "residual": 0.030155920515246765
          },
          {
            "gap_min": 155.58999999999992,
            "gap_max": 254.41999999999985,
            "gap_mean": 194.744414893617,
            "n": 94,
            "observed_p_mean": 0.2590776595744681,
            "predicted_e_mean": 0.27284253185539487,
            "residual": -0.013764872280926765
          }
        ],
        "total_pairs": 940,
        "calibration_mae": 0.016970576612683096
      },
      "self_consistency": {
        "n_players": 23,
        "n_excluded_below_floor": 12,
        "min_matches_threshold": 10,
        "spearman_rho": 0.8142292490118577,
        "mean_abs_half_diff": 0.08240920536194934
      },
      "bootstrap": {
        "runs": 100,
        "sample_rate": 0.8,
        "n_matches_total": 107,
        "n_sampled_per_run": 85,
        "top_n": 20,
        "jaccard_mean": 0.8259759081498212,
        "jaccard_median": 0.8181818181818182,
        "jaccard_min": 0.6666666666666666,
        "jaccard_max": 1.0,
        "proxy_std_median": 31.948613317482188,
        "proxy_std_mean": 29.254569630169428,
        "proxy_std_max": 48.98374741268782,
        "n_players_with_proxy_std": 35,
        "meanP_std_median": 0.021648908296681195,
        "meanP_std_mean": 0.029071558878884504
      },
      "synthetic_winner": {
        "n_eligible": 32,
        "n_agreements": 32,
        "agreement": 1.0,
        "agreement_ci": [
          0.8928172849426366,
          1.0
        ],
        "passes_threshold": true,
        "threshold": 0.85,
        "disagreements": []
      },
      "clean_win_accuracy": {
        "n_eligible": 32,
        "n_correct": 12,
        "accuracy": 0.375,
        "accuracy_ci": [
          0.2293366846595921,
          0.5474589941047487
        ],
        "log_loss_mean": 0.7073412851123143,
        "log_loss_median": 0.705329473761853,
        "log_loss_coin_flip": 0.6931471805599453,
        "skillbench_anchors": {
          "winrate_baseline_pct": 0.6,
          "elo_pct": 0.62,
          "glicko2_pct": 0.64,
          "trueskill_pct": 0.629,
          "trueskill_players_pct": 0.641
        },
        "aggregations": {
          "mean": {
            "n_eligible": 32,
            "n_correct": 12,
            "accuracy": 0.375,
            "accuracy_ci": [
              0.2293366846595921,
              0.5474589941047487
            ],
            "log_loss_mean": 0.7073412851123143,
            "log_loss_median": 0.705329473761853
          },
          "hard_max": {
            "n_eligible": 32,
            "n_correct": 16,
            "accuracy": 0.5,
            "accuracy_ci": [
              0.33630614316859386,
              0.6636938568314061
            ],
            "log_loss_mean": 0.7291700294055822,
            "log_loss_median": 0.6994138894122496
          },
          "softmax_max": {
            "n_eligible": 32,
            "n_correct": 13,
            "accuracy": 0.40625,
            "accuracy_ci": [
              0.255194024803138,
              0.5774027342701177
            ],
            "log_loss_mean": 0.7179606503264057,
            "log_loss_median": 0.6984294439882933
          }
        },
        "best_aggregation": "hard_max",
        "softmax_tau": 200.0,
        "commander_breakout": {
          "with_commander": {
            "n_eligible": 32,
            "n_correct": 12,
            "accuracy": 0.375,
            "accuracy_ci": [
              0.2293366846595921,
              0.5474589941047487
            ],
            "log_loss_mean": 0.7073412851123143,
            "log_loss_median": 0.705329473761853
          },
          "all_thug": {
            "n_eligible": 0,
            "n_correct": 0,
            "accuracy": null,
            "accuracy_ci": [
              null,
              null
            ],
            "log_loss_mean": null,
            "log_loss_median": null
          },
          "n_with_commander": 32,
          "n_all_thug": 0
        },
        "rating_gap_breakout": {
          "buckets": [
            {
              "bucket": "small",
              "gap_min": 0.0,
              "gap_max": 25.0,
              "n": 17,
              "score": {
                "n_eligible": 17,
                "n_correct": 8,
                "accuracy": 0.47058823529411764,
                "accuracy_ci": [
                  0.26164801196088106,
                  0.6903710268845051
                ],
                "log_loss_mean": 0.6929440341937615,
                "log_loss_median": 0.7002744357010802
              },
              "mean_gap_in_bucket": 11.976421568627423
            },
            {
              "bucket": "mid",
              "gap_min": 25.0,
              "gap_max": 100.0,
              "n": 15,
              "score": {
                "n_eligible": 15,
                "n_correct": 4,
                "accuracy": 0.26666666666666666,
                "accuracy_ci": [
                  0.1089727610318281,
                  0.5195088965768675
                ],
                "log_loss_mean": 0.7236581694866742,
                "log_loss_median": 0.7416808516680047
              },
              "mean_gap_in_bucket": 46.06089999999996
            },
            {
              "bucket": "large",
              "gap_min": 100.0,
              "gap_max": null,
              "n": 0,
              "score": {
                "n_eligible": 0,
                "n_correct": 0,
                "accuracy": null,
                "accuracy_ci": [
                  null,
                  null
                ],
                "log_loss_mean": null,
                "log_loss_median": null
              },
              "mean_gap_in_bucket": 0.0
            }
          ]
        }
      },
      "axis_ablation": {
        "baseline_top_n": [
          "76561198076339639",
          "76561197974548434",
          "76561198045727092",
          "76561198877763773",
          "76561198824607769",
          "76561198006115793",
          "76561198079394192",
          "76561198043392032",
          "76561198074300787",
          "76561198088149233",
          "76561199066952713",
          "76561198345909972",
          "76561198123805650",
          "76561199653748651",
          "76561198025032941",
          "76561198045619216",
          "76561198026325621",
          "76561198284800778",
          "76561198068133931",
          "76561198825004088"
        ],
        "n_players_pool": 35,
        "top_n": 20,
        "results": [
          {
            "axis_dropped": "net_damage_share",
            "weight_redirected": 0.2,
            "spearman_vs_baseline": 0.94593837535014,
            "top_n_jaccard": 0.9047619047619048,
            "n_players": 35
          },
          {
            "axis_dropped": "thug_kill_rate",
            "weight_redirected": 0.2,
            "spearman_vs_baseline": 0.9686274509803922,
            "top_n_jaccard": 1.0,
            "n_players": 35
          },
          {
            "axis_dropped": "thug_accuracy",
            "weight_redirected": 0.15,
            "spearman_vs_baseline": 0.9703081232492997,
            "top_n_jaccard": 0.9047619047619048,
            "n_players": 35
          },
          {
            "axis_dropped": "pve_share",
            "weight_redirected": 0.12,
            "spearman_vs_baseline": 0.9736694677871148,
            "top_n_jaccard": 1.0,
            "n_players": 35
          },
          {
            "axis_dropped": "thug_efficiency",
            "weight_redirected": 0.16,
            "spearman_vs_baseline": 0.9742296918767507,
            "top_n_jaccard": 0.9047619047619048,
            "n_players": 35
          },
          {
            "axis_dropped": "mobility",
            "weight_redirected": 0.08,
            "spearman_vs_baseline": 0.9904761904761905,
            "top_n_jaccard": 1.0,
            "n_players": 35
          },
          {
            "axis_dropped": "target_lock_pct",
            "weight_redirected": 0.005,
            "spearman_vs_baseline": 0.9997198879551821,
            "top_n_jaccard": 1.0,
            "n_players": 35
          },
          {
            "axis_dropped": "snipe_bonus",
            "weight_redirected": 0.005,
            "spearman_vs_baseline": 1.0,
            "top_n_jaccard": 1.0,
            "n_players": 35
          }
        ]
      },
      "dirichlet": {
        "runs": 50,
        "concentration": 50.0,
        "top_n": 20,
        "rho_mean": 0.9824481792717087,
        "rho_median": 0.9864145658263306,
        "rho_min": 0.9375350140056022,
        "rho_max": 0.9983193277310924,
        "rho_stdev": 0.013600483737375204,
        "jaccard_mean": 0.9716017316017316,
        "jaccard_median": 1.0,
        "jaccard_min": 0.8181818181818182
      },
      "winner_funnel": {
        "rated_history_entries": 107,
        "missing_per_match_file": 0,
        "winner_block_missing": 0,
        "decided_by_clean_win": 32,
        "decided_by_contested": 1,
        "decided_by_unclear": 74,
        "skipped_no_team_split": 0
      }
    }
  },
  "validator_trend": [
    {
      "run": "Phase 1 (v3 doc)",
      "date": "2026-05-30",
      "rated": 100,
      "spearman": 0.462,
      "self_consistency": 0.804,
      "synthetic": 93.3,
      "cleanwin_mean": 43.3,
      "cleanwin_max": 53.3,
      "boot_sigma": 27.0,
      "n_cleanwin": 30
    },
    {
      "run": "June 5 (schema 8)",
      "date": "2026-06-05",
      "rated": 103,
      "spearman": 0.468,
      "self_consistency": 0.82,
      "synthetic": 90.3,
      "cleanwin_mean": 45.2,
      "cleanwin_max": 48.4,
      "boot_sigma": 29.4,
      "n_cleanwin": 31
    },
    {
      "run": "Fresh (v2.10, this report)",
      "date": "2026-06-10",
      "rated": 107,
      "spearman": null,
      "self_consistency": null,
      "synthetic": null,
      "cleanwin_mean": null,
      "cleanwin_max": null,
      "boot_sigma": null,
      "n_cleanwin": null
    }
  ],
  "lowtier_lift": {
    "enabled": true,
    "cutoff": 1460.0,
    "taper": 60.0,
    "axis": "thug_kill_rate",
    "min_ship_minutes": 2.0,
    "eligible_count": 10
  }
};
